[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "ffmpeg-python>=0.2.0",
    "moviepy>=2.2.1",
    "numpy>=2.2.6",
    "openai-whisper>=20250625",
]
